// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"
	"github.com/manhhung2111/go-idm/internal/app"
	"github.com/manhhung2111/go-idm/internal/config"
	"github.com/manhhung2111/go-idm/internal/dataaccess"
	"github.com/manhhung2111/go-idm/internal/dataaccess/cache"
	"github.com/manhhung2111/go-idm/internal/dataaccess/database"
	"github.com/manhhung2111/go-idm/internal/dataaccess/file"
	"github.com/manhhung2111/go-idm/internal/dataaccess/kafka/consumer"
	"github.com/manhhung2111/go-idm/internal/dataaccess/kafka/producer"
	"github.com/manhhung2111/go-idm/internal/handler"
	"github.com/manhhung2111/go-idm/internal/handler/consumer"
	"github.com/manhhung2111/go-idm/internal/handler/grpc"
	"github.com/manhhung2111/go-idm/internal/handler/http"
	"github.com/manhhung2111/go-idm/internal/logic"
	"github.com/manhhung2111/go-idm/internal/utils"
)

// Injectors from wire.go:

func InitializeServer(configFilePath config.ConfigFilePath) (*app.Server, func(), error) {
	configConfig, err := config.NewConfig(configFilePath)
	if err != nil {
		return nil, nil, err
	}
	configDatabase := configConfig.Database
	db, cleanup, err := database.InitializeDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	log := configConfig.Log
	logger, cleanup2, err := utils.InitializeLogger(log)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	accountDataAccessor := database.NewAccountDataAccessor(goquDatabase, logger)
	accountPasswordDataAccessor := database.NewAccountPasswordDataAccessor(goquDatabase, logger)
	auth := configConfig.Auth
	hash := logic.NewHash(auth)
	token, err := logic.NewToken(accountDataAccessor, auth, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configCache := configConfig.Cache
	cacheClient := cache.NewRedisClient(configCache, logger)
	accountNameCache := cache.NewAccountNameCache(cacheClient, logger)
	account := logic.NewAccount(goquDatabase, accountDataAccessor, accountPasswordDataAccessor, hash, token, accountNameCache, logger)
	downloadTaskDataAccessor := database.NewDownloadTaskDataAccessor(goquDatabase, logger)
	kafka := configConfig.Kafka
	client, err := producer.NewClient(kafka, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	downloadTaskCreatedProducer := producer.NewDownloadTaskCreatedProducer(client, logger)
	download := configConfig.Download
	fileClient, err := file.NewClient(download, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	downloadTask := logic.NewDownloadTask(token, accountDataAccessor, downloadTaskDataAccessor, goquDatabase, logger, downloadTaskCreatedProducer, fileClient)
	configGRPC := configConfig.GRPC
	goIDMServiceServer, err := grpc.NewHandler(account, downloadTask, configGRPC)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server := grpc.NewServer(goIDMServiceServer, configGRPC, logger)
	configHTTP := configConfig.HTTP
	httpServer := http.NewServer(configGRPC, configHTTP, logger)
	downloadTaskCreateHandler := handler_consumer.NewDownloadTaskCreatedHandler(downloadTask, logger)
	consumerConsumer, err := consumer.NewConsumer(kafka, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	root := handler_consumer.NewRoot(downloadTaskCreateHandler, consumerConsumer, logger)
	appServer := app.NewServer(server, httpServer, root, logger)
	return appServer, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(config.WireSet, dataaccess.WireSet, handler.WireSet, logic.WireSet, utils.WireSet, app.WireSet)
