// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"
	"github.com/manhhung2111/go-idm/internal/config"
	"github.com/manhhung2111/go-idm/internal/dataaccess"
	"github.com/manhhung2111/go-idm/internal/dataaccess/database"
	"github.com/manhhung2111/go-idm/internal/handler"
	"github.com/manhhung2111/go-idm/internal/handler/grpc"
	"github.com/manhhung2111/go-idm/internal/logic"
)

// Injectors from wire.go:

func InitializeGrpcServer(configFilePath config.ConfigFilePath) (grpc.Server, func(), error) {
	configConfig, err := config.NewConfig(configFilePath)
	if err != nil {
		return nil, nil, err
	}
	configDatabase := configConfig.Database
	db, cleanup, err := database.InitializeDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	accountDataAccessor := database.NewAccountDataAccessor(goquDatabase)
	accountPasswordDataAccessor := database.NewAccountPasswordDataAccessor(goquDatabase)
	account := configConfig.Account
	hash := logic.NewHash(account)
	logicAccount := logic.NewAccount(goquDatabase, accountDataAccessor, accountPasswordDataAccessor, hash)
	goIDMServiceServer := grpc.NewHandler(logicAccount)
	server := grpc.NewServer(goIDMServiceServer)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(config.WireSet, dataaccess.WireSet, handler.WireSet, logic.WireSet)
