// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"
	"github.com/manhhung2111/go-idm/internal/config"
	"github.com/manhhung2111/go-idm/internal/dataaccess"
	"github.com/manhhung2111/go-idm/internal/dataaccess/database"
	"github.com/manhhung2111/go-idm/internal/handler"
	"github.com/manhhung2111/go-idm/internal/handler/grpc"
	"github.com/manhhung2111/go-idm/internal/logic"
	"github.com/manhhung2111/go-idm/internal/utils"
)

// Injectors from wire.go:

func InitializeGrpcServer(configFilePath config.ConfigFilePath) (grpc.Server, func(), error) {
	configConfig, err := config.NewConfig(configFilePath)
	if err != nil {
		return nil, nil, err
	}
	configDatabase := configConfig.Database
	db, cleanup, err := database.InitializeDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	log := configConfig.Log
	logger, cleanup2, err := utils.InitializeLogger(log)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	accountDataAccessor := database.NewAccountDataAccessor(goquDatabase, logger)
	accountPasswordDataAccessor := database.NewAccountPasswordDataAccessor(goquDatabase, logger)
	auth := configConfig.Auth
	hash := logic.NewHash(auth)
	token, err := logic.NewToken(accountDataAccessor, auth, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	account := logic.NewAccount(goquDatabase, accountDataAccessor, accountPasswordDataAccessor, hash, token)
	goIDMServiceServer := grpc.NewHandler(account)
	server := grpc.NewServer(goIDMServiceServer)
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(config.WireSet, dataaccess.WireSet, handler.WireSet, logic.WireSet, utils.WireSet)
